# EXERCISE 1 IMPORT PANDAS, MATPLOTLIB AND SEABORNS

In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# TO READ THE DATASET USING PANDAS

In [4]:
df = pd.read_csv("telecom_churn.csv")

In [5]:
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77,26.55,215.5,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3329,WV,68,415,No,No,0,231.1,57,39.29,153.4,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
3330,RI,28,510,No,No,0,180.8,109,30.74,288.8,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3331,CT,184,510,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False
3332,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

# TO BE ABLE TO SEE ALL THE COLUMNS

In [6]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,3323,3324,3325,3326,3327,3328,3329,3330,3331,3332
State,KS,OH,NJ,OH,OK,AL,MA,MO,LA,WV,...,IN,WV,OH,OH,SC,AZ,WV,RI,CT,TN
Account length,128,107,137,84,75,118,121,147,117,141,...,117,159,78,96,79,192,68,28,184,74
Area code,415,415,415,408,415,510,510,415,408,415,...,415,415,408,415,415,415,415,510,510,415
International plan,No,No,No,Yes,Yes,Yes,No,Yes,No,Yes,...,No,No,No,No,No,No,No,No,Yes,No
Voice mail plan,Yes,Yes,No,No,No,No,Yes,No,No,Yes,...,No,No,No,No,No,Yes,No,No,No,Yes
Number vmail messages,25,26,0,0,0,0,24,0,0,37,...,0,0,0,0,0,36,0,0,0,25
Total day minutes,265.1,161.6,243.4,299.4,166.7,223.4,218.2,157.0,184.5,258.6,...,118.4,169.8,193.4,106.6,134.7,156.2,231.1,180.8,213.8,234.4
Total day calls,110,123,114,71,113,98,88,79,97,84,...,126,114,99,128,98,77,57,109,105,113
Total day charge,45.07,27.47,41.38,50.9,28.34,37.98,37.09,26.69,31.37,43.96,...,20.13,28.87,32.88,18.12,22.9,26.55,39.29,30.74,36.35,39.85
Total eve minutes,197.4,195.5,121.2,61.9,148.3,220.6,348.5,103.1,351.6,222.0,...,249.3,197.7,116.9,284.8,189.7,215.5,153.4,288.8,159.6,265.9
Total eve calls,99,103,110,88,122,101,108,94,80,111,...,97,105,88,87,68,126,55,58,84,82
Total eve charge,16.78,16.62,10.3,5.26,12.61,18.75,29.62,8.76,29.89,18.87,...,21.19,16.8,9.94,24.21,16.12,18.32,13.04,24.55,13.57,22.6
Total night minutes,244.7,254.4,162.6,196.9,186.9,203.9,212.6,211.8,215.8,326.4,...,227.0,193.7,243.3,178.9,221.4,279.1,191.3,191.9,139.2,241.4
Total night calls,91,103,104,89,121,118,118,96,90,97,...,56,82,109,92,128,83,123,91,137,77
Total night charge,11.01,11.45,7.32,8.86,8.41,9.18,9.57,9.53,9.71,14.69,...,10.22,8.72,10.95,8.05,9.96,12.56,8.61,8.64,6.26,10.86
Total intl minutes,10.0,13.7,12.2,6.6,10.1,6.3,7.5,7.1,8.7,11.2,...,13.6,11.6,9.3,14.9,11.8,9.9,9.6,14.1,5.0,13.7
Total intl calls,3,3,5,7,3,6,7,6,4,5,...,3,4,4,7,5,6,4,6,10,4
Total intl charge,2.7,3.7,3.29,1.78,2.73,1.7,2.03,1.92,2.35,3.02,...,3.67,3.13,2.51,4.02,3.19,2.67,2.59,3.81,1.35,3.7
Customer service calls,1,1,0,2,3,0,3,0,1,0,...,5,1,2,1,2,2,3,2,2,0
Churn,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False

# check the dimensinality of the dataframe by printing the shape of the dataframe

In [7]:
df.shape

(3333, 20)